In [1]:
from pinnsform import *

In [3]:
time_slice_loss = np.array([7.2915, 7.2541, 7.2168, 7.1796, 7.1425, 7.1056, 7.0689, 7.0322, 6.9958,
        6.9594, 6.9232, 6.8872, 6.8512, 6.8154, 6.7798, 6.7443, 6.7089, 6.6737,
        6.6386, 6.6036, 6.5688, 6.5341, 6.4996, 6.4652, 6.4309, 6.3968, 6.3628,
        6.3290, 6.2953, 6.2617, 6.2283, 6.1950, 6.1618, 6.1288, 6.0959, 6.0631,
        6.0305, 5.9980, 5.9657, 5.9335, 5.9014, 5.8695, 5.8377, 5.8060, 5.7745,
        5.7431, 5.7118, 5.6807, 5.6497, 5.6189, 5.5881, 5.5576, 5.5271, 5.4968,
        5.4666, 5.4365, 5.4066, 5.3768, 5.3472, 5.3177, 5.2883, 5.2590, 5.2299,
        5.2009, 5.1721, 5.1433, 5.1147, 5.0863, 5.0579, 5.0297, 5.0016, 4.9737,
        4.9459, 4.9182, 4.8906, 4.8632, 4.8359, 4.8087, 4.7817, 4.7548, 4.7280,
        4.7013, 4.6748, 4.6484, 4.6221, 4.5960, 4.5700, 4.5441, 4.5183, 4.4927,
        4.4672, 4.4418, 4.4165, 4.3913, 4.3663, 4.3414, 4.3167, 4.2920, 4.2675,
        4.2431, 4.2188])

In [12]:
np.roll(time_slice_loss, 1)

array([4.2188, 7.2915, 7.2541, 7.2168, 7.1796, 7.1425, 7.1056, 7.0689,
       7.0322, 6.9958, 6.9594, 6.9232, 6.8872, 6.8512, 6.8154, 6.7798,
       6.7443, 6.7089, 6.6737, 6.6386, 6.6036, 6.5688, 6.5341, 6.4996,
       6.4652, 6.4309, 6.3968, 6.3628, 6.329 , 6.2953, 6.2617, 6.2283,
       6.195 , 6.1618, 6.1288, 6.0959, 6.0631, 6.0305, 5.998 , 5.9657,
       5.9335, 5.9014, 5.8695, 5.8377, 5.806 , 5.7745, 5.7431, 5.7118,
       5.6807, 5.6497, 5.6189, 5.5881, 5.5576, 5.5271, 5.4968, 5.4666,
       5.4365, 5.4066, 5.3768, 5.3472, 5.3177, 5.2883, 5.259 , 5.2299,
       5.2009, 5.1721, 5.1433, 5.1147, 5.0863, 5.0579, 5.0297, 5.0016,
       4.9737, 4.9459, 4.9182, 4.8906, 4.8632, 4.8359, 4.8087, 4.7817,
       4.7548, 4.728 , 4.7013, 4.6748, 4.6484, 4.6221, 4.596 , 4.57  ,
       4.5441, 4.5183, 4.4927, 4.4672, 4.4418, 4.4165, 4.3913, 4.3663,
       4.3414, 4.3167, 4.292 , 4.2675, 4.2431])

In [15]:
time_slice_loss_rolled = np.roll(time_slice_loss, 1)
time_slice_loss_rolled[0] = 0.5519
cumsum = np.cumsum(time_slice_loss_rolled) + 1

In [16]:
cumsum

array([  1.5519,   8.8434,  16.0975,  23.3143,  30.4939,  37.6364,
        44.742 ,  51.8109,  58.8431,  65.8389,  72.7983,  79.7215,
        86.6087,  93.4599, 100.2753, 107.0551, 113.7994, 120.5083,
       127.182 , 133.8206, 140.4242, 146.993 , 153.5271, 160.0267,
       166.4919, 172.9228, 179.3196, 185.6824, 192.0114, 198.3067,
       204.5684, 210.7967, 216.9917, 223.1535, 229.2823, 235.3782,
       241.4413, 247.4718, 253.4698, 259.4355, 265.369 , 271.2704,
       277.1399, 282.9776, 288.7836, 294.5581, 300.3012, 306.013 ,
       311.6937, 317.3434, 322.9623, 328.5504, 334.108 , 339.6351,
       345.1319, 350.5985, 356.035 , 361.4416, 366.8184, 372.1656,
       377.4833, 382.7716, 388.0306, 393.2605, 398.4614, 403.6335,
       408.7768, 413.8915, 418.9778, 424.0357, 429.0654, 434.067 ,
       439.0407, 443.9866, 448.9048, 453.7954, 458.6586, 463.4945,
       468.3032, 473.0849, 477.8397, 482.5677, 487.269 , 491.9438,
       496.5922, 501.2143, 505.8103, 510.3803, 514.9244, 519.4

In [17]:
1/cumsum

array([0.64437142, 0.11307868, 0.06212145, 0.04289213, 0.03279344,
       0.02657002, 0.02235036, 0.01930096, 0.01699435, 0.01518859,
       0.01373658, 0.01254367, 0.01154618, 0.01069978, 0.00997255,
       0.00934098, 0.00878739, 0.00829818, 0.00786275, 0.00747269,
       0.00712128, 0.00680305, 0.00651351, 0.00624896, 0.0060063 ,
       0.00578293, 0.00557664, 0.00538554, 0.00520802, 0.00504269,
       0.00488834, 0.00474391, 0.00460847, 0.00448122, 0.00436144,
       0.00424848, 0.00414179, 0.00404086, 0.00394524, 0.00385452,
       0.00376834, 0.00368636, 0.00360829, 0.00353385, 0.0034628 ,
       0.00339492, 0.00332999, 0.00326784, 0.00320828, 0.00315116,
       0.00309634, 0.00304367, 0.00299304, 0.00294434, 0.00289744,
       0.00285227, 0.00280871, 0.0027667 , 0.00272614, 0.00268698,
       0.00264912, 0.00261252, 0.00257712, 0.00254284, 0.00250965,
       0.0024775 , 0.00244632, 0.00241609, 0.00238676, 0.00235829,
       0.00233065, 0.00230379, 0.00227769, 0.00225232, 0.00222

In [18]:
before = np.array([[9.3388e-02, 2.1368e-02, 1.4239e-05, 2.0693e-02, 7.4962e-02],
        [1.5722e+00, 1.1137e+00, 7.4698e-01, 4.6434e-01, 2.5745e-01],
        [5.4261e+00, 4.4745e+00, 3.6300e+00, 2.8904e+00, 2.2518e+00],
        [1.1695e+01, 1.0323e+01, 9.0402e+00, 7.8498e+00, 6.7536e+00],
        [1.9779e+01, 1.8167e+01, 1.6608e+01, 1.5107e+01, 1.3669e+01]])

after = np.array([[6.1825e-02, 2.3029e-03, 8.8129e-07, 9.3119e-04, 2.7207e-03],
        [1.0408e+00, 1.2003e-01, 4.6233e-02, 2.0895e-02, 9.3441e-03],
        [3.5922e+00, 4.8222e-01, 2.2467e-01, 1.3006e-01, 8.1727e-02],
        [7.7426e+00, 1.1125e+00, 5.5953e-01, 3.5324e-01, 2.4512e-01],
        [1.3094e+01, 1.9579e+00, 1.0279e+00, 6.7981e-01, 4.9613e-01]])

In [22]:
np.mean(before, axis=0)

array([7.7131376 , 6.8199136 , 6.00503885, 5.2664466 , 4.6013624 ])

In [23]:
np.mean(after, axis=0)

array([5.106285  , 0.73499058, 0.37166678, 0.23698724, 0.16700836])

In [24]:
np.mean(after, axis=0)/np.mean(before, axis=0)

array([0.66202436, 0.10777125, 0.06189248, 0.04499946, 0.03629542])