In [57]:
from pinnsform import *

In [2]:
mesh, borders = generate_mesh_object((3,3,3), domain=[[0,2*np.pi], [0,1], [0,1]], device="cpu", full_requires_grad=True, border_requires_grad=False, num_seq_steps=3, seq_step_size=0.01)

In [3]:
mesh.part[0]

tensor([[[0.0000, 0.0000],
         [0.0000, 0.0000],
         [0.0000, 0.0000]],

        [[0.0000, 0.0000],
         [0.0000, 0.0000],
         [0.0000, 0.0000]],

        [[0.0000, 0.0000],
         [0.0000, 0.0000],
         [0.0000, 0.0000]],

        [[0.0000, 0.5000],
         [0.0000, 0.5000],
         [0.0000, 0.5000]],

        [[0.0000, 0.5000],
         [0.0000, 0.5000],
         [0.0000, 0.5000]],

        [[0.0000, 0.5000],
         [0.0000, 0.5000],
         [0.0000, 0.5000]],

        [[0.0000, 1.0000],
         [0.0000, 1.0000],
         [0.0000, 1.0000]],

        [[0.0000, 1.0000],
         [0.0000, 1.0000],
         [0.0000, 1.0000]],

        [[0.0000, 1.0000],
         [0.0000, 1.0000],
         [0.0000, 1.0000]],

        [[3.1416, 0.0000],
         [3.1416, 0.0000],
         [3.1416, 0.0000]],

        [[3.1416, 0.0000],
         [3.1416, 0.0000],
         [3.1416, 0.0000]],

        [[3.1416, 0.0000],
         [3.1416, 0.0000],
         [3.1416, 0.0000]],

    

In [4]:
def meshify(l, device, requires_grad = False, mode = 'normal'):
    base_np_mesh = np.array(list(product(*l))
    if mode == 'normal':
        parts = [torch.tensor(part, requires_grad = requires_grad, dtype=torch.get_default_dtype()).to(device) for part in np.array_split(base_np_mesh, 2, 1)]
        full = torch.cat(parts, dim=1)
        return Mesh(full, parts)

def generate_mesh_object(point_counts, domain, skew = None, meshify_mode = 'normal', device = 'cpu', full_requires_grad = True, border_requires_grad = False):
    if isinstance(point_counts, int):
        point_counts = [point_counts]
        domain = [domain]

    if skew:
        full_list = [np.linspace(0, 1, count) for i, count in enumerate(point_counts)]
        full_list = [points ** skew[i] for i, points in enumerate(full_list)]
        full_list = [domain[i][0] + (domain[i][1] - domain[i][0]) * points for i,points in enumerate(full_list)]
    else:
        full_list = [np.linspace(domain[i][0], domain[i][1], count) for i, count in enumerate(point_counts)]
    
    full_mesh = meshify(full_list, device, full_requires_grad)
    
    border_lists = [(copy(full_list), copy(full_list)) for _ in full_list]
    for i, _ in enumerate(full_list):
        border_lists[i][0][i] = [float(domain[i][0])]
        border_lists[i][1][i] = [float(domain[i][1])]
    border_meshes = [(meshify(border[0], device, border_requires_grad), meshify(border[1], device, border_requires_grad)) for border in border_lists]
    
    return full_mesh, border_meshes

SyntaxError: invalid syntax (1937736472.py, line 3)

In [5]:
counts = (5,5)
domain = ((0,1), (0, np.pi))

In [5]:
if isinstance(counts, int):
    counts = [counts]
    domain = [domain]

In [6]:
full_list = [np.linspace(domain[i][0], domain[i][1], count) for i, count in enumerate(counts)]

In [7]:
full_list

[array([0.  , 0.25, 0.5 , 0.75, 1.  ]),
 array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265])]

In [8]:
np_mesh = np.array(list(product(*full_list)))

In [9]:
np_mesh

array([[0.        , 0.        ],
       [0.        , 0.78539816],
       [0.        , 1.57079633],
       [0.        , 2.35619449],
       [0.        , 3.14159265],
       [0.25      , 0.        ],
       [0.25      , 0.78539816],
       [0.25      , 1.57079633],
       [0.25      , 2.35619449],
       [0.25      , 3.14159265],
       [0.5       , 0.        ],
       [0.5       , 0.78539816],
       [0.5       , 1.57079633],
       [0.5       , 2.35619449],
       [0.5       , 3.14159265],
       [0.75      , 0.        ],
       [0.75      , 0.78539816],
       [0.75      , 1.57079633],
       [0.75      , 2.35619449],
       [0.75      , 3.14159265],
       [1.        , 0.        ],
       [1.        , 0.78539816],
       [1.        , 1.57079633],
       [1.        , 2.35619449],
       [1.        , 3.14159265]])

In [10]:
shuffled_mesh = np.random.shuffle(np_mesh)

In [13]:
np_mesh

array([[0.5       , 0.        ],
       [1.        , 1.57079633],
       [0.5       , 1.57079633],
       [0.        , 3.14159265],
       [1.        , 3.14159265],
       [0.75      , 2.35619449],
       [0.        , 2.35619449],
       [0.75      , 0.        ],
       [0.75      , 3.14159265],
       [0.        , 0.        ],
       [1.        , 0.78539816],
       [0.25      , 0.        ],
       [0.75      , 1.57079633],
       [0.5       , 3.14159265],
       [0.25      , 0.78539816],
       [0.25      , 2.35619449],
       [0.5       , 0.78539816],
       [0.75      , 0.78539816],
       [0.        , 1.57079633],
       [0.        , 0.78539816],
       [1.        , 2.35619449],
       [0.25      , 3.14159265],
       [0.25      , 1.57079633],
       [0.5       , 2.35619449],
       [1.        , 0.        ]])

In [14]:
split_mesh = np.array_split(np_mesh, 3)

In [15]:
split_mesh

[array([[0.5       , 0.        ],
        [1.        , 1.57079633],
        [0.5       , 1.57079633],
        [0.        , 3.14159265],
        [1.        , 3.14159265],
        [0.75      , 2.35619449],
        [0.        , 2.35619449],
        [0.75      , 0.        ],
        [0.75      , 3.14159265]]),
 array([[0.        , 0.        ],
        [1.        , 0.78539816],
        [0.25      , 0.        ],
        [0.75      , 1.57079633],
        [0.5       , 3.14159265],
        [0.25      , 0.78539816],
        [0.25      , 2.35619449],
        [0.5       , 0.78539816]]),
 array([[0.75      , 0.78539816],
        [0.        , 1.57079633],
        [0.        , 0.78539816],
        [1.        , 2.35619449],
        [0.25      , 3.14159265],
        [0.25      , 1.57079633],
        [0.5       , 2.35619449],
        [1.        , 0.        ]])]

In [9]:
mesh, borders = generate_mesh_object((5,5), domain=[[0,2*np.pi], [0,1], [0,1]], device="cpu", full_requires_grad=True, border_requires_grad=False)

In [10]:
mesh.full

tensor([[0.0000, 0.0000],
        [0.0000, 0.2500],
        [0.0000, 0.5000],
        [0.0000, 0.7500],
        [0.0000, 1.0000],
        [1.5708, 0.0000],
        [1.5708, 0.2500],
        [1.5708, 0.5000],
        [1.5708, 0.7500],
        [1.5708, 1.0000],
        [3.1416, 0.0000],
        [3.1416, 0.2500],
        [3.1416, 0.5000],
        [3.1416, 0.7500],
        [3.1416, 1.0000],
        [4.7124, 0.0000],
        [4.7124, 0.2500],
        [4.7124, 0.5000],
        [4.7124, 0.7500],
        [4.7124, 1.0000],
        [6.2832, 0.0000],
        [6.2832, 0.2500],
        [6.2832, 0.5000],
        [6.2832, 0.7500],
        [6.2832, 1.0000]], grad_fn=<CatBackward0>)

In [11]:
model = nn.Linear(in_features=2, out_features=128)

In [15]:
out = model(mesh.full)

In [19]:
print(out)
print(out.shape)

tensor([[-0.3784,  0.3807, -0.3268,  ...,  0.5858, -0.3674,  0.6199],
        [-0.3450,  0.2402, -0.3355,  ...,  0.4460, -0.5375,  0.6092],
        [-0.3117,  0.0996, -0.3443,  ...,  0.3061, -0.7076,  0.5985],
        ...,
        [-1.9083, -3.0675, -1.0781,  ...,  3.0758, -5.0830,  3.9713],
        [-1.8750, -3.2080, -1.0868,  ...,  2.9360, -5.2532,  3.9606],
        [-1.8417, -3.3485, -1.0955,  ...,  2.7962, -5.4233,  3.9500]],
       grad_fn=<AddmmBackward0>)
torch.Size([25, 128])


In [13]:
generator = torch.Generator()
generator.manual_seed(0)
act1 = WaveActAll(128, generator)

In [20]:
act1(out)

sin(x) shape torch.Size([25, 128])
w1 shape torch.Size([128])


tensor([[-0.4050, -0.8171, -0.6818,  ...,  0.7646,  1.4443,  1.1237],
        [-0.4505, -0.6810, -0.6774,  ...,  0.6330,  1.1618,  1.1140],
        [-0.4955, -0.5315, -0.6730,  ...,  0.4891,  0.8458,  1.1042],
        ...,
        [ 1.3549,  0.5031, -0.1599,  ..., -0.0679,  1.5499, -1.2870],
        [ 1.3388,  0.3415, -0.1527,  ...,  0.0961,  1.7712, -1.2800],
        [ 1.3212,  0.1732, -0.1455,  ...,  0.2582,  1.9413, -1.2729]],
       grad_fn=<AddBackward0>)

In [58]:
torch.Tensor(np.array([[0,1], [0,1], [0,1], [0,1], [0,1]])).shape

torch.Size([5, 2])

In [97]:
def make_spatial_sequence(src, num_step, step_size, domain):
    dim = num_step
    src = np.repeat(np.expand_dims(src, axis=1), dim, axis=1)  # (N, L, 2)
    #print(src)
    spatial_domain = np.array(domain)[0:-1]
    for i in range(0, src.shape[0]):
        for j in range(1, num_step):
            base_value = src[i,j,0:1]
            offset = step_size*int((j+1)/2)*(-1)**j
            if base_value[0] == domain[0][0]:
                offset = step_size*j
            if base_value[0] == domain[0][1]:
                offset = -step_size*j
            print(base_value)
            src[i,j,0:1] += offset
    return src

In [98]:
problem_domain = ([0, 2*np.pi], [0, 1], [0,60])
device = "cpu"
train_points = (3, 3, 3) 

# 51x51 mesh as list
np_mesh = generate_mesh(train_points, problem_domain)
# 51x51 mesh as list with temporal sequence for every point
sequence_mesh = make_spatial_sequence(np_mesh, num_step=5, step_size=1e-2, domain=problem_domain)
# flatten the temporal sequence for normal models
#np_mesh_sequence = listify_sequence(sequence_mesh)
# make Mesh object of torch tensors
#mesh = torchify(sequence_mesh, device, True)
#boundaries = torchified_borders(sequence_mesh, problem_domain, device, False)



[0.]
[0.]
[0.]
[0.]
[0.]
[0.]
[0.]
[0.]
[0.]
[0.]
[0.]
[0.]
[0.]
[0.]
[0.]
[0.]
[0.]
[0.]
[0.]
[0.]
[0.]
[0.]
[0.]
[0.]
[0.]
[0.]
[0.]
[0.]
[0.]
[0.]
[0.]
[0.]
[0.]
[0.]
[0.]
[0.]
[3.14159265]
[3.14159265]
[3.14159265]
[3.14159265]
[3.14159265]
[3.14159265]
[3.14159265]
[3.14159265]
[3.14159265]
[3.14159265]
[3.14159265]
[3.14159265]
[3.14159265]
[3.14159265]
[3.14159265]
[3.14159265]
[3.14159265]
[3.14159265]
[3.14159265]
[3.14159265]
[3.14159265]
[3.14159265]
[3.14159265]
[3.14159265]
[3.14159265]
[3.14159265]
[3.14159265]
[3.14159265]
[3.14159265]
[3.14159265]
[3.14159265]
[3.14159265]
[3.14159265]
[3.14159265]
[3.14159265]
[3.14159265]
[6.28318531]
[6.28318531]
[6.28318531]
[6.28318531]
[6.28318531]
[6.28318531]
[6.28318531]
[6.28318531]
[6.28318531]
[6.28318531]
[6.28318531]
[6.28318531]
[6.28318531]
[6.28318531]
[6.28318531]
[6.28318531]
[6.28318531]
[6.28318531]
[6.28318531]
[6.28318531]
[6.28318531]
[6.28318531]
[6.28318531]
[6.28318531]
[6.28318531]
[6.28318531]
[6.28318531]
[

In [99]:
sequence_mesh

array([[[0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [1.00000000e-02, 0.00000000e+00, 0.00000000e+00],
        [2.00000000e-02, 0.00000000e+00, 0.00000000e+00],
        [3.00000000e-02, 0.00000000e+00, 0.00000000e+00],
        [4.00000000e-02, 0.00000000e+00, 0.00000000e+00]],

       [[0.00000000e+00, 0.00000000e+00, 3.00000000e+01],
        [1.00000000e-02, 0.00000000e+00, 3.00000000e+01],
        [2.00000000e-02, 0.00000000e+00, 3.00000000e+01],
        [3.00000000e-02, 0.00000000e+00, 3.00000000e+01],
        [4.00000000e-02, 0.00000000e+00, 3.00000000e+01]],

       [[0.00000000e+00, 0.00000000e+00, 6.00000000e+01],
        [1.00000000e-02, 0.00000000e+00, 6.00000000e+01],
        [2.00000000e-02, 0.00000000e+00, 6.00000000e+01],
        [3.00000000e-02, 0.00000000e+00, 6.00000000e+01],
        [4.00000000e-02, 0.00000000e+00, 6.00000000e+01]],

       [[0.00000000e+00, 5.00000000e-01, 0.00000000e+00],
        [1.00000000e-02, 5.00000000e-01, 0.00000000e+00],
        

In [50]:
class WaveActCorrect(nn.Module):
    def __init__(self, layer_size):
        super(WaveActCorrect, self).__init__()
        self.w1 = nn.Parameter(torch.randn(layer_size), requires_grad=False)
        self.w2 = nn.Parameter(torch.randn(layer_size), requires_grad=False)

    def forward(self, x):
        return self.w1 * torch.sin(x) + self.w2 * torch.cos(x)

In [51]:
print(mesh.full)

tensor([[[0.0000e+00, 0.0000e+00],
         [0.0000e+00, 1.0000e-03],
         [0.0000e+00, 2.0000e-03]],

        [[0.0000e+00, 1.0000e+00],
         [0.0000e+00, 1.0010e+00],
         [0.0000e+00, 1.0020e+00]],

        [[6.2832e+00, 0.0000e+00],
         [6.2832e+00, 1.0000e-03],
         [6.2832e+00, 2.0000e-03]],

        [[6.2832e+00, 1.0000e+00],
         [6.2832e+00, 1.0010e+00],
         [6.2832e+00, 1.0020e+00]]], grad_fn=<CatBackward0>)


In [53]:
act1 = WaveActCorrect(1)
act2 = WaveActCorrect(2)

In [54]:
for param in act1.parameters():
    print(param)
print()
for param in act2.parameters():
    print(param)

Parameter containing:
tensor([-0.9043])
Parameter containing:
tensor([0.5738])

Parameter containing:
tensor([-0.1026, -0.6055])
Parameter containing:
tensor([0.0029, 1.2671])


In [56]:
print(mesh.full)
print(act1(mesh.full))
print(act2(mesh.full))

tensor([[[0.0000e+00, 0.0000e+00],
         [0.0000e+00, 1.0000e-03],
         [0.0000e+00, 2.0000e-03]],

        [[0.0000e+00, 1.0000e+00],
         [0.0000e+00, 1.0010e+00],
         [0.0000e+00, 1.0020e+00]],

        [[6.2832e+00, 0.0000e+00],
         [6.2832e+00, 1.0000e-03],
         [6.2832e+00, 2.0000e-03]],

        [[6.2832e+00, 1.0000e+00],
         [6.2832e+00, 1.0010e+00],
         [6.2832e+00, 1.0020e+00]]], grad_fn=<CatBackward0>)
tensor([[[ 0.5738,  0.5738],
         [ 0.5738,  0.5729],
         [ 0.5738,  0.5720]],

        [[ 0.5738, -0.4509],
         [ 0.5738, -0.4519],
         [ 0.5738, -0.4529]],

        [[ 0.5738,  0.5738],
         [ 0.5738,  0.5729],
         [ 0.5738,  0.5720]],

        [[ 0.5738, -0.4509],
         [ 0.5738, -0.4519],
         [ 0.5738, -0.4529]]], grad_fn=<AddBackward0>)
tensor([[[0.0029, 1.2671],
         [0.0029, 1.2665],
         [0.0029, 1.2659]],

        [[0.0029, 0.1751],
         [0.0029, 0.1737],
         [0.0029, 0.1723]],

  

In [9]:
def meshify_sequence(sequence_mesh):
    return np.reshape(sequence_mesh, (sequence_mesh.shape[0]*sequence_mesh.shape[1], 2))

In [25]:
meshify_sequence(sequence_mesh)

array([[0.        , 0.        ],
       [0.        , 0.01      ],
       [0.        , 0.02      ],
       ...,
       [6.28318531, 1.02      ],
       [6.28318531, 1.03      ],
       [6.28318531, 1.04      ]])

In [22]:
for collocation_point in meshified_sequence:
    print(collocation_point)

[0. 0.]
[0.   0.01]
[0.   0.02]
[0.   0.03]
[0.   0.04]
[0.  0.1]
[0.   0.11]
[0.   0.12]
[0.   0.13]
[0.   0.14]
[0.  0.2]
[0.   0.21]
[0.   0.22]
[0.   0.23]
[0.   0.24]
[0.  0.3]
[0.   0.31]
[0.   0.32]
[0.   0.33]
[0.   0.34]
[0.  0.4]
[0.   0.41]
[0.   0.42]
[0.   0.43]
[0.   0.44]
[0.  0.5]
[0.   0.51]
[0.   0.52]
[0.   0.53]
[0.   0.54]
[0.  0.6]
[0.   0.61]
[0.   0.62]
[0.   0.63]
[0.   0.64]
[0.  0.7]
[0.   0.71]
[0.   0.72]
[0.   0.73]
[0.   0.74]
[0.  0.8]
[0.   0.81]
[0.   0.82]
[0.   0.83]
[0.   0.84]
[0.  0.9]
[0.   0.91]
[0.   0.92]
[0.   0.93]
[0.   0.94]
[0. 1.]
[0.   1.01]
[0.   1.02]
[0.   1.03]
[0.   1.04]
[0.62831853 0.        ]
[0.62831853 0.01      ]
[0.62831853 0.02      ]
[0.62831853 0.03      ]
[0.62831853 0.04      ]
[0.62831853 0.1       ]
[0.62831853 0.11      ]
[0.62831853 0.12      ]
[0.62831853 0.13      ]
[0.62831853 0.14      ]
[0.62831853 0.2       ]
[0.62831853 0.21      ]
[0.62831853 0.22      ]
[0.62831853 0.23      ]
[0.62831853 0.24      ]
[0.628